# Generated by Django 4.0.3 on 2022-03-21 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('user_id', models.CharField(default='', max_length=35)),
                ('username', models.CharField(default='', max_length=100, unique=True)),
                ('email', models.CharField(default='', max_length=100, unique=True)),
                ('linkedIn', models.CharField(default='', max_length=100)),
                ('twitter', models.CharField(default='', max_length=100)),
                ('website', models.CharField(default='', max_length=100)),
            ],
        ),
    ]
